### ISSUE TITLE
_TZE200_3towulqd TS0601 Tuya motion+illuminance sensor, cannot set keep time and sensitivity [BUG]

### ISSUE THREAD

**Issue by jure123** [zigpy/zha-device-handlers#2190]
**Describe the bug**
I've been using the quark that @javicalle suggested for the _TZE200_3towulqd TS0601 motion+illuminance sensor. Sensor is working fine, but I cannot set keep_time and sensitivity settings. Tried on multiple devices. 

I am aware the device is a low power device and reading/setting values can be difficult, and were trying to write values when sersor detected motion (like written here: https://github.com/jaspernlp/zigbee2mqtt.io/blob/master/docs/devices/ZG-204ZL.md#reading-and-setting-values)

I also tried to set my devices with Zigbee2Mqtt, where setting keep_time and sensitivity values worked fine. Only in ZHA not working.

**To Reproduce**
1. Installed ZHA and add the ZHA quirk as suggest here - https://github.com/zigpy/zha-device-handlers/issues/1599
2. Tried to write **keep_time** of value **2** (60 seconds). I was repeatedly and rapidly pushing the write attribute button when sensor was changing occupancy state to ensure the data should be received by the device (pushing the write repeadely and quickly 2-times per second).
3. Pushing the read attribute button showed "**OnTimeValues._60_SEC**" as expected (however I suspect the value was read from some internal cache, because pushing the read button always shows the value immediately, no matter if sensor is changing state or is inactive). Not sure if I really receive the actual value stored on the device.
4. **The sensor still cleared the occupancy state after 15 seconds** (as a default keep time value), and not after 60 seconds as it would be expected.
5. Resetting HASS, and reading keep time attribute still shows **OnTimeValues._60_SEC**, but the device still clearing state after 15 seconds. I suspect the read attribute button show value from some internal cache? (because pushing the read button always shows the value immediately, no matter if sensor is changing state or is inactive).

<details>
<summary>Debug log</summary>

```
2023-02-12 13:15:57.621 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] write_attributes --> record: Attribute(attrid=0xEF0A, value=TypeValue(type=OnTimeValues, value=<OnTimeValues._60_SEC: 2>))
2023-02-12 13:15:57.623 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] tuya_mcu_command: cluster_data=TuyaClusterData(endpoint_id=1, cluster_name='tuya_manufacturer', cluster_attr='keep_time', attr_value=<OnTimeValues._60_SEC: 2>, expect_reply=False)
2023-02-12 13:15:57.623 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] get_dp_mapping --> found DP: 10
2023-02-12 13:15:57.623 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] from_cluster_data: {10: DPToAttributeMapping(ep_attribute='tuya_manufacturer', attribute_name='keep_time', dp_type=<TuyaDPType.ENUM: 4>, converter=<function PirMotionManufCluster.<lambda> at 0x7f9725f370>, dp_converter=None, endpoint_id=None)}
2023-02-12 13:15:57.624 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] value: OnTimeValues._60_SEC
2023-02-12 13:15:57.624 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] raw: b'\x02'
2023-02-12 13:15:57.625 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] tuya_commands: [TuyaCommand(status=0, tsn=125, datapoints=[TuyaDatapointData(dp=10, data=TuyaData(dp_type=<TuyaDPType.ENUM: 4>, function=0, raw=b'\x02', *payload=<enum8.undefined_0x02: 2>))])]
2023-02-12 13:15:57.628 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x218F](TS0601): set: 2 for attr: 61194 to cluster: 61184 for ept: 1 - res: [[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]]
2023-02-12 13:15:57.629 DEBUG (MainThread) [homeassistant.components.zha.api] Set attribute for: cluster_id: [61184] cluster_type: [in] endpoint_id: [1] attribute: [61194] value: [2] manufacturer: [None] response: [[[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]]]
2023-02-12 13:15:57.631 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=True, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), manufacturer=4417, tsn=126, command_id=0, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
2023-02-12 13:15:57.632 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Sending request: set_data(data=TuyaCommand(status=0, tsn=125, datapoints=[TuyaDatapointData(dp=10, data=TuyaData(dp_type=<TuyaDPType.ENUM: 4>, function=0, raw=b'\x02', *payload=<enum8.undefined_0x02: 2>))]))
2023-02-12 13:15:57.634 DEBUG (MainThread) [bellows.zigbee.application] Sending packet ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x218F), dst_ep=1, source_route=None, extended_timeout=False, tsn=126, profile_id=260, cluster_id=61184, data=Serialized[b'\x05A\x11~\x00\x00}\n\x04\x00\x01\x02'], tx_options=<TransmitOptions.ACK: 1>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2023-02-12 13:15:57.635 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'INSERT INTO attributes_cache_v11 VALUES (?, ?, ?, ?, ?)\n                    ON CONFLICT (ieee, endpoint_id, cluster, attrid)\n                    DO UPDATE SET\n                        value=excluded.value WHERE value != excluded.value', (a4:c1:38:5f:56:df:dc:b0, 1, 61184, 61194, '2'))
2023-02-12 13:15:57.634 DEBUG (MainThread) [bellows.ezsp.protocol] Send command sendUnicast: (<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 0x218f, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=126), 127, b'\x05A\x11~\x00\x00}\n\x04\x00\x01\x02')
2023-02-12 13:15:57.636 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'318821a9602a153d78904b25455493099d4e27d592c262caecb8638981743ba7eacfadc67e'
2023-02-12 13:15:57.637 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'INSERT INTO attributes_cache_v11 VALUES (?, ?, ?, ?, ?)\n                    ON CONFLICT (ieee, endpoint_id, cluster, attrid)\n                    DO UPDATE SET\n                        value=excluded.value WHERE value != excluded.value', (a4:c1:38:5f:56:df:dc:b0, 1, 61184, 61194, '2')) completed
2023-02-12 13:15:57.642 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>)
2023-02-12 13:15:57.642 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>) completed
2023-02-12 13:15:57.644 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'INSERT INTO attributes_cache_v11 VALUES (?, ?, ?, ?, ?)\n                    ON CONFLICT (ieee, endpoint_id, cluster, attrid)\n                    DO UPDATE SET\n                        value=excluded.value WHERE value != excluded.value', (a4:c1:38:5f:56:df:dc:b0, 1, 61184, 61194, <OnTimeValues._60_SEC: 2>))
2023-02-12 13:15:57.645 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'INSERT INTO attributes_cache_v11 VALUES (?, ?, ?, ?, ?)\n                    ON CONFLICT (ieee, endpoint_id, cluster, attrid)\n                    DO UPDATE SET\n                        value=excluded.value WHERE value != excluded.value', (a4:c1:38:5f:56:df:dc:b0, 1, 61184, 61194, <OnTimeValues._60_SEC: 2>)) completed
2023-02-12 13:15:57.647 DEBUG (bellows.thread_0) [bellows.uart] Data frame: b'1488a1a9602a156e74187e'
2023-02-12 13:15:57.647 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'82503a7e'
2023-02-12 13:15:57.648 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received sendUnicast: [<EmberStatus.SUCCESS: 0>, 220]
2023-02-12 13:15:57.649 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>)
2023-02-12 13:15:57.650 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>) completed
2023-02-12 13:15:58.577 DEBUG (bellows.thread_0) [bellows.uart] Data frame: b'2488b1a9112a15b65894a524ab5593499cdbb76b62ef9874f0cf628bfc5b33a5ebc9de6f8c7da8c17e'
2023-02-12 13:15:58.577 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'83401b7e'
2023-02-12 13:15:58.581 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received incomingMessageHandler: [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY: 256>, groupId=0, sequence=149), 144, -64, 0x218f, 255, 255, b'\t\x01\x02\x00%\x0c\x02\x00\x04\x00\x00\x03\x82']
2023-02-12 13:15:58.582 DEBUG (MainThread) [bellows.zigbee.application] Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY: 256>, groupId=0, sequence=149), 144, -64, 0x218f, 255, 255, b'\t\x01\x02\x00%\x0c\x02\x00\x04\x00\x00\x03\x82']
2023-02-12 13:15:58.583 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x218F), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=149, profile_id=260, cluster_id=61184, data=Serialized[b'\t\x01\x02\x00%\x0c\x02\x00\x04\x00\x00\x03\x82'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=144, rssi=-64)
2023-02-12 13:15:58.584 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Received ZCL frame: b'\t\x01\x02\x00%\x0c\x02\x00\x04\x00\x00\x03\x82'
2023-02-12 13:15:58.587 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=True), tsn=1, command_id=2, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
2023-02-12 13:15:58.590 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Decoded ZCL frame: PirMotionManufCluster:set_data_response(data=TuyaCommand(status=0, tsn=37, datapoints=[TuyaDatapointData(dp=12, data=TuyaData(dp_type=<TuyaDPType.VALUE: 2>, function=0, raw=b'\x00\x00\x03\x82', *payload=898))]))
2023-02-12 13:15:58.591 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Received command 0x02 (TSN 1): set_data_response(data=TuyaCommand(status=0, tsn=37, datapoints=[TuyaDatapointData(dp=12, data=TuyaData(dp_type=<TuyaDPType.VALUE: 2>, function=0, raw=b'\x00\x00\x03\x82', *payload=898))]))
2023-02-12 13:15:58.595 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'UPDATE devices_v11\n                    SET last_seen=:ts\n                    WHERE ieee=:ieee AND :ts - last_seen > :min_last_seen_delta', {'ts': 1676204158.584559, 'ieee': a4:c1:38:5f:56:df:dc:b0, 'min_last_seen_delta': 30.0})
2023-02-12 13:15:58.596 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'UPDATE devices_v11\n                    SET last_seen=:ts\n                    WHERE ieee=:ieee AND :ts - last_seen > :min_last_seen_delta', {'ts': 1676204158.584559, 'ieee': a4:c1:38:5f:56:df:dc:b0, 'min_last_seen_delta': 30.0}) completed
2023-02-12 13:15:58.601 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Sending reply header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=1, command_id=<GeneralCommand.Default_Response: 11>, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
2023-02-12 13:15:58.602 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Sending reply: Default_Response(command_id=2, status=<Status.SUCCESS: 0>)
2023-02-12 13:15:58.602 DEBUG (MainThread) [bellows.zigbee.application] Sending packet ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x218F), dst_ep=1, source_route=None, extended_timeout=False, tsn=1, profile_id=260, cluster_id=61184, data=Serialized[b'\x18\x01\x0b\x02\x00'], tx_options=<TransmitOptions.ACK: 1>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2023-02-12 13:15:58.603 DEBUG (MainThread) [bellows.ezsp.protocol] Send command sendUnicast: (<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 0x218f, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=1), 128, b'\x18\x01\x0b\x02\x00')
2023-02-12 13:15:58.605 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'438921a9602a153d78904b25455493099d4e27aa6dcb7f8af6c46349497e'
2023-02-12 13:15:58.608 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>)
2023-02-12 13:15:58.611 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>) completed
2023-02-12 13:15:58.613 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'INSERT INTO attributes_cache_v11 VALUES (?, ?, ?, ?, ?)\n                    ON CONFLICT (ieee, endpoint_id, cluster, attrid)\n                    DO UPDATE SET\n                        value=excluded.value WHERE value != excluded.value', (a4:c1:38:5f:56:df:dc:b0, 1, 1024, 0, 29533.763366673043))
2023-02-12 13:15:58.614 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'INSERT INTO attributes_cache_v11 VALUES (?, ?, ?, ?, ?)\n                    ON CONFLICT (ieee, endpoint_id, cluster, attrid)\n                    DO UPDATE SET\n                        value=excluded.value WHERE value != excluded.value', (a4:c1:38:5f:56:df:dc:b0, 1, 1024, 0, 29533.763366673043)) completed
2023-02-12 13:15:58.615 DEBUG (bellows.thread_0) [bellows.uart] Data frame: b'3589a1a9602a156fe0e37e'
2023-02-12 13:15:58.616 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'8430fc7e'
2023-02-12 13:15:58.617 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>)
2023-02-12 13:15:58.617 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received sendUnicast: [<EmberStatus.SUCCESS: 0>, 221]
2023-02-12 13:15:58.621 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>) completed
2023-02-12 13:15:58.830 DEBUG (bellows.thread_0) [bellows.uart] Data frame: b'4589b1a96b2a153d78904b25455493099d4e277792ce67ed0e7e'
2023-02-12 13:15:58.830 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'8520dd7e'
2023-02-12 13:15:58.834 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received messageSentHandler: [<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 8591, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=220), 127, <EmberStatus.SUCCESS: 0>, b'']
2023-02-12 13:15:58.835 DEBUG (MainThread) [bellows.zigbee.application] Received messageSentHandler frame with [<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 8591, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=220), 127, <EmberStatus.SUCCESS: 0>, b'']
2023-02-12 13:15:58.851 DEBUG (bellows.thread_0) [bellows.uart] Data frame: b'5589b1a9112a15b65894a524ab5593499cd8bf6962ef9874f8de1d82fcfd62c27e'
2023-02-12 13:15:58.852 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'8610be7e'
2023-02-12 13:15:58.853 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received incomingMessageHandler: [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY: 256>, groupId=0, sequence=150), 152, -62, 0x218f, 255, 255, b'\x18~\x0b\x00\x83']
2023-02-12 13:15:58.853 DEBUG (MainThread) [bellows.zigbee.application] Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY: 256>, groupId=0, sequence=150), 152, -62, 0x218f, 255, 255, b'\x18~\x0b\x00\x83']
2023-02-12 13:15:58.854 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x218F), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=150, profile_id=260, cluster_id=61184, data=Serialized[b'\x18~\x0b\x00\x83'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=152, rssi=-62)
2023-02-12 13:15:58.854 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Received ZCL frame: b'\x18~\x0b\x00\x83'
2023-02-12 13:15:58.855 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=126, command_id=11, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
2023-02-12 13:15:58.856 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Decoded ZCL frame: PirMotionManufCluster:Default_Response(command_id=0, status=<Status.UNSUP_MANUF_CLUSTER_COMMAND: 131>)
2023-02-12 13:15:58.857 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Received command 0x0B (TSN 126): Default_Response(command_id=0, status=<Status.UNSUP_MANUF_CLUSTER_COMMAND: 131>)
2023-02-12 13:15:58.860 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'UPDATE devices_v11\n                    SET last_seen=:ts\n                    WHERE ieee=:ieee AND :ts - last_seen > :min_last_seen_delta', {'ts': 1676204158.854649, 'ieee': a4:c1:38:5f:56:df:dc:b0, 'min_last_seen_delta': 30.0})
2023-02-12 13:15:58.861 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'UPDATE devices_v11\n                    SET last_seen=:ts\n                    WHERE ieee=:ieee AND :ts - last_seen > :min_last_seen_delta', {'ts': 1676204158.854649, 'ieee': a4:c1:38:5f:56:df:dc:b0, 'min_last_seen_delta': 30.0}) completed
2023-02-12 13:15:58.864 DEBUG (bellows.thread_0) [bellows.uart] Data frame: b'6589b1a96b2a153d78904b25455493099d4e27766dce6734357e'
2023-02-12 13:15:58.864 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'87009f7e'
2023-02-12 13:15:58.865 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>)
2023-02-12 13:15:58.867 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received messageSentHandler: [<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 8591, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=221), 128, <EmberStatus.SUCCESS: 0>, b'']
2023-02-12 13:15:58.868 DEBUG (MainThread) [bellows.zigbee.application] Received messageSentHandler frame with [<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 8591, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=221), 128, <EmberStatus.SUCCESS: 0>, b'']
2023-02-12 13:15:58.868 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>) completed
2023-02-12 13:15:58.882 DEBUG (bellows.thread_0) [bellows.uart] Data frame: b'7589b1a9112a15b65894a524ab5593499cd9b36a62ef9874f7cf618bfc583ea3ebccdef6f67e'
2023-02-12 13:15:58.883 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'8070787e'
2023-02-12 13:15:58.886 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received incomingMessageHandler: [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY: 256>, groupId=0, sequence=151), 148, -63, 0x218f, 255, 255, b'\t\x02\x02\x00&\x01\x04\x00\x01\x00']
2023-02-12 13:15:58.887 DEBUG (MainThread) [bellows.zigbee.application] Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY: 256>, groupId=0, sequence=151), 148, -63, 0x218f, 255, 255, b'\t\x02\x02\x00&\x01\x04\x00\x01\x00']
2023-02-12 13:15:58.887 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x218F), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=151, profile_id=260, cluster_id=61184, data=Serialized[b'\t\x02\x02\x00&\x01\x04\x00\x01\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=148, rssi=-63)
2023-02-12 13:15:58.888 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Received ZCL frame: b'\t\x02\x02\x00&\x01\x04\x00\x01\x00'
2023-02-12 13:15:58.889 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=True), tsn=2, command_id=2, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
2023-02-12 13:15:58.890 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Decoded ZCL frame: PirMotionManufCluster:set_data_response(data=TuyaCommand(status=0, tsn=38, datapoints=[TuyaDatapointData(dp=1, data=TuyaData(dp_type=<TuyaDPType.ENUM: 4>, function=0, raw=b'\x00', *payload=<enum8.undefined_0x00: 0>))]))
2023-02-12 13:15:58.891 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Received command 0x02 (TSN 2): set_data_response(data=TuyaCommand(status=0, tsn=38, datapoints=[TuyaDatapointData(dp=1, data=TuyaData(dp_type=<TuyaDPType.ENUM: 4>, function=0, raw=b'\x00', *payload=<enum8.undefined_0x00: 0>))]))
2023-02-12 13:15:58.894 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'UPDATE devices_v11\n                    SET last_seen=:ts\n                    WHERE ieee=:ieee AND :ts - last_seen > :min_last_seen_delta', {'ts': 1676204158.887854, 'ieee': a4:c1:38:5f:56:df:dc:b0, 'min_last_seen_delta': 30.0})
2023-02-12 13:15:58.897 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'UPDATE devices_v11\n                    SET last_seen=:ts\n                    WHERE ieee=:ieee AND :ts - last_seen > :min_last_seen_delta', {'ts': 1676204158.887854, 'ieee': a4:c1:38:5f:56:df:dc:b0, 'min_last_seen_delta': 30.0}) completed
2023-02-12 13:15:58.898 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Sending reply header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True, *is_reply=True), tsn=2, command_id=<GeneralCommand.Default_Response: 11>, *direction=<Direction.Client_to_Server: 1>, *is_reply=True)
2023-02-12 13:15:58.899 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Sending reply: Default_Response(command_id=2, status=<Status.SUCCESS: 0>)
2023-02-12 13:15:58.900 DEBUG (MainThread) [bellows.zigbee.application] Sending packet ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x218F), dst_ep=1, source_route=None, extended_timeout=False, tsn=2, profile_id=260, cluster_id=61184, data=Serialized[b'\x18\x02\x0b\x02\x00'], tx_options=<TransmitOptions.ACK: 1>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2023-02-12 13:15:58.900 DEBUG (MainThread) [bellows.ezsp.protocol] Send command sendUnicast: (<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 0x218f, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=2), 129, b'\x18\x02\x0b\x02\x00')
2023-02-12 13:15:58.905 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'508e21a9602a153d78904b25455493099d4e27a96ccb7f89f6c463ae2e7e'
2023-02-12 13:15:58.906 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>)
2023-02-12 13:15:58.906 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>) completed
2023-02-12 13:15:58.908 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'INSERT INTO attributes_cache_v11 VALUES (?, ?, ?, ?, ?)\n                    ON CONFLICT (ieee, endpoint_id, cluster, attrid)\n                    DO UPDATE SET\n                        value=excluded.value WHERE value != excluded.value', (a4:c1:38:5f:56:df:dc:b0, 1, 1030, 0, <ZoneStatus.Alarm_1: 1>))
2023-02-12 13:15:58.908 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f97adf440>, 'INSERT INTO attributes_cache_v11 VALUES (?, ?, ?, ?, ?)\n                    ON CONFLICT (ieee, endpoint_id, cluster, attrid)\n                    DO UPDATE SET\n                        value=excluded.value WHERE value != excluded.value', (a4:c1:38:5f:56:df:dc:b0, 1, 1030, 0, <ZoneStatus.Alarm_1: 1>)) completed
2023-02-12 13:15:58.909 DEBUG (Thread-3) [aiosqlite] executing functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>)
2023-02-12 13:15:58.911 DEBUG (Thread-3) [aiosqlite] operation functools.partial(<built-in method commit of sqlite3.Connection object at 0x7f97adf440>) completed
2023-02-12 13:15:58.916 DEBUG (bellows.thread_0) [bellows.uart] Data frame: b'068ea1a9602a156c476d7e'
2023-02-12 13:15:58.917 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'8160597e'
2023-02-12 13:15:58.919 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received sendUnicast: [<EmberStatus.SUCCESS: 0>, 222]
2023-02-12 13:15:58.948 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x683D](TS0001): Device seen - marking the device available and resetting counter
2023-02-12 13:15:58.948 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x683D](TS0001): Update device availability -  device available: True - new availability: True - changed: False
2023-02-12 13:15:59.048 DEBUG (bellows.thread_0) [bellows.uart] Data frame: b'168eb1a96b2a153d78904b25455493099d4e27756cce67b7af7e'
2023-02-12 13:15:59.049 DEBUG (bellows.thread_0) [bellows.uart] Sending: b'82503a7e'
2023-02-12 13:15:59.053 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received messageSentHandler: [<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 8591, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=222), 129, <EmberStatus.SUCCESS: 0>, b'']
2023-02-12 13:15:59.053 DEBUG (MainThread) [bellows.zigbee.application] Received messageSentHandler frame with [<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 8591, EmberApsFrame(profileId=260, clusterId=61184, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=222), 129, <EmberStatus.SUCCESS: 0>, b'']
2023-02-12 13:16:00.136 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] write_attributes --> record: Attribute(attrid=0xEF0A, value=TypeValue(type=OnTimeValues, value=<OnTimeValues._60_SEC: 2>))
2023-02-12 13:16:00.138 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] tuya_mcu_command: cluster_data=TuyaClusterData(endpoint_id=1, cluster_name='tuya_manufacturer', cluster_attr='keep_time', attr_value=<OnTimeValues._60_SEC: 2>, expect_reply=False)
2023-02-12 13:16:00.138 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] get_dp_mapping --> found DP: 10
2023-02-12 13:16:00.139 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] from_cluster_data: {10: DPToAttributeMapping(ep_attribute='tuya_manufacturer', attribute_name='keep_time', dp_type=<TuyaDPType.ENUM: 4>, converter=<function PirMotionManufCluster.<lambda> at 0x7f9725f370>, dp_converter=None, endpoint_id=None)}
2023-02-12 13:16:00.139 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] value: OnTimeValues._60_SEC
2023-02-12 13:16:00.140 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] raw: b'\x02'
2023-02-12 13:16:00.140 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] tuya_commands: [TuyaCommand(status=0, tsn=130, datapoints=[TuyaDatapointData(dp=10, data=TuyaData(dp_type=<TuyaDPType.ENUM: 4>, function=0, raw=b'\x02', *payload=<enum8.undefined_0x02: 2>))])]
2023-02-12 13:16:00.143 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x218F](TS0601): set: 2 for attr: 61194 to cluster: 61184 for ept: 1 - res: [[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]]
2023-02-12 13:16:00.143 DEBUG (MainThread) [homeassistant.components.zha.api] Set attribute for: cluster_id: [61184] cluster_type: [in] endpoint_id: [1] attribute: [61194] value: [2] manufacturer: [None] response: [[[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]]]
2023-02-12 13:16:00.144 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=True, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False, *is_reply=False), manufacturer=4417, tsn=131, command_id=0, *direction=<Direction.Server_to_Client: 0>, *is_reply=False)
2023-02-12 13:16:00.145 DEBUG (MainThread) [zigpy.zcl] [0x218F:1:0xef00] Sending request: set_data(data=TuyaCommand(status=0, tsn=130, datapoints=[TuyaDatapointData(dp=10, data=TuyaData(dp_type=<TuyaDPType.ENUM: 4>, function=0, raw=b'\x02', *payload=<enum8.undefined_0x02: 2>))]))
```

</details>

<details>
<summary>Diagnostic information</summary>

```json
 "data": {
    "ieee": "**REDACTED**",
    "nwk": 8591,
    "manufacturer": "_TZE200_3towulqd",
    "model": "TS0601",
    "name": "_TZE200_3towulqd TS0601",
    "quirk_applied": true,
    "quirk_class": "ts0601_pirmotion.PirMotion",
    "manufacturer_code": 4417,
    "power_source": "Battery or Unknown",
    "lqi": 144,
    "rssi": -64,
    "last_seen": "2023-02-12T14:01:02",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0402",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0400",
            "0x0406",
            "0xef00"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "binary_sensor.senzor_occupancy",
        "name": "_TZE200_3towulqd TS0601"
      },
      {
        "entity_id": "sensor.senzor_battery",
        "name": "_TZE200_3towulqd TS0601"
      },
      {
        "entity_id": "sensor.senzor_illuminance",
        "name": "_TZE200_3towulqd TS0601"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "IAS_ZONE"
      }
    ],
    "user_given_name": "Senzor",
    "device_reg_id": "243be9c646ffcebe2c898c3deada82c1",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "IAS_ZONE",
          "id": 1026
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "_TZE200_3towulqd"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "TS0601"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0021": {
                "attribute_name": "battery_percentage_remaining",
                "value": 100
              }
            },
            "unsupported_attributes": {
              "0x0031": {
                "attribute_name": "battery_size"
              },
              "0x0033": {
                "attribute_name": "battery_quantity"
              }
            }
          },
          "0xef00": {
            "endpoint_attribute": "tuya_manufacturer",
            "attributes": {
              "0xef09": {
                "attribute_name": "sensitivity_level",
                "value": 2
              },
              "0xef0a": {
                "attribute_name": "keep_time",
                "value": 2
              }
            },
            "unsupported_attributes": {}
          },
          "0x0406": {
            "endpoint_attribute": "occupancy",
            "attributes": {
              "0x0000": {
                "attribute_name": "occupancy",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          },
          "0x0400": {
            "endpoint_attribute": "illuminance",
            "attributes": {
              "0x0000": {
                "attribute_name": "measured_value",
                "value": 29648.309210536292
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
```

</details>

BTW: in the logs I noticed below line that sends the keep time attribute to the device, and getting `Status.SUCCESS: 0` response. Should this line get `Status.SUCCESS: 1` on successful update? I tried for several times and logs only contain Status.SUCCESS: 0.

`[homeassistant.components.zha.api] Set attribute for: cluster_id: [61184] cluster_type: [in] endpoint_id: [1] attribute: [61194] value: [2] manufacturer: [None] response: [[[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]]]`

**Comment by javicalle** [comment]
A couple of comments:
* Which HA version are you running? You have an `UNSUP_MANUF_CLUSTER_COMMAND` that must not be there.
* That `Status.SUCCESS: 0` is the Status identifier (and not a boolean value). All the posible values are defined here:
https://github.com/zigpy/zigpy/blob/819f8e7dc97e27627335a398dac22ad9a9b7688a/zigpy/zcl/foundation.py#L25-L62
* Try to remove the battery from device and put it on again. At this moment usually the device reports all the current values (and its DPs). That information would give us some clues about what can be happening.

**Comment by jure123** [comment]
I'm running Home Assistant 2023.2.3 (and the same problem on older versions from 2023, but before that I didn't have these sensor devices yet).

I removed the battery from device, after that it showed keep_time OnTimeValues._10_SEC.

**Comment by jure123** [comment]
This is my full diagnostic:

<details>

```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.2.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Vienna",
    "os_name": "Linux",
    "os_version": "5.15.84-v8",
    "supervisor": "2023.01.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "xiaomi_miot": {
      "version": "0.7.5",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "localtuya": {
      "version": "5.0.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.7",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.92",
      "zigpy-deconz==0.19.2",
      "zigpy==0.53.0",
      "zigpy-xbee==0.16.2",
      "zigpy-zigate==0.10.3",
      "zigpy-znp==0.9.2"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 8591,
    "manufacturer": "_TZE200_3towulqd",
    "model": "TS0601",
    "name": "_TZE200_3towulqd TS0601",
    "quirk_applied": true,
    "quirk_class": "ts0601_pirmotion.PirMotion",
    "manufacturer_code": 4417,
    "power_source": "Battery or Unknown",
    "lqi": 144,
    "rssi": -64,
    "last_seen": "2023-02-12T17:18:20",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0402",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0400",
            "0x0406",
            "0xef00"
          ],
          "out_clusters": [
            "0x000a",
            "0x0019"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "binary_sensor.senzor",
        "name": "_TZE200_3towulqd TS0601"
      },
      {
        "entity_id": "sensor.senzor",
        "name": "_TZE200_3towulqd TS0601"
      },
      {
        "entity_id": "sensor.senzor",
        "name": "_TZE200_3towulqd TS0601"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "IAS_ZONE"
      }
    ],
    "user_given_name": "Senzor",
    "device_reg_id": "243be9c646ffcebe2c898c3deada82c1",
    "area_id": "kuhinja",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "IAS_ZONE",
          "id": 1026
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "_TZE200_3towulqd"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "TS0601"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0021": {
                "attribute_name": "battery_percentage_remaining",
                "value": 200
              }
            },
            "unsupported_attributes": {
              "0x0031": {
                "attribute_name": "battery_size"
              },
              "0x0033": {
                "attribute_name": "battery_quantity"
              }
            }
          },
          "0xef00": {
            "endpoint_attribute": "tuya_manufacturer",
            "attributes": {
              "0xef09": {
                "attribute_name": "sensitivity_level",
                "value": 2
              },
              "0xef0a": {
                "attribute_name": "keep_time",
                "value": 2
              }
            },
            "unsupported_attributes": {}
          },
          "0x0406": {
            "endpoint_attribute": "occupancy",
            "attributes": {
              "0x0000": {
                "attribute_name": "occupancy",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          },
          "0x0400": {
            "endpoint_attribute": "illuminance",
            "attributes": {
              "0x0000": {
                "attribute_name": "measured_value",
                "value": 20935.21685162235
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

**Comment by javicalle** [comment]
I'm not sure  which is the exact version for your quirk but I would say that the `UNSUP_MANUF_CLUSTER_COMMAND` is related t the Tuya `NO_MANUFACTURER_ID` issue...

I would suggest to try with this changes:
1. import the `foundation` package:
```python
from zigpy.zcl import foundation
```
2. update the `PirMotionManufCluster` class adding the `write_attributes` method like that:
```python
class PirMotionManufCluster(TuyaMCUCluster):
    """Tuya manufacturer cluster."""

    attributes = TuyaMCUCluster.attributes.copy()
    attributes.update({0xEF09: ("sensitivity_level", SensitivityLevel)})
    attributes.update({0xEF0A: ("keep_time", OnTimeValues)})

    async def write_attributes(self, attributes, manufacturer=None):
        """Overwrite to force manufacturer code."""

        return await super().write_attributes(
            attributes, manufacturer=foundation.ZCLHeader.NO_MANUFACTURER_ID
        )

    dp_to_attribute: Dict[int, DPToAttributeMapping] = {
        .../...
```

Save changes, delete any `__pycache__` folder and restart HA.
Check if the `UNSUP_MANUF_CLUSTER_COMMAND` error is still showing up in your traces.

**Comment by jure123** [comment]
Your suggestion fixed my issue!

Here is my fixed quirk:

<details>

<summary>ts0601_pirmotion.py</summary>

```py
"""BlitzWolf IS-3/Tuya motion rechargeable occupancy sensor."""

import math
from typing import Dict

from zigpy.profiles import zha
from zigpy.quirks import CustomDevice
import zigpy.types as t
from zigpy.zcl.clusters.general import Basic, Ota, Time
from zigpy.zcl.clusters.measurement import IlluminanceMeasurement, OccupancySensing
from zigpy.zcl.clusters.security import IasZone
from zigpy.zcl import foundation

from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
)
from zhaquirks.tuya import TuyaLocalCluster
from zhaquirks.tuya.mcu import (
    DPToAttributeMapping,
    TuyaDPType,
    TuyaMCUCluster,
    TuyaPowerConfigurationCluster,
)

class TuyaOccupancySensing(OccupancySensing, TuyaLocalCluster):
    """Tuya local OccupancySensing cluster."""


class TuyaIlluminanceMeasurement(IlluminanceMeasurement, TuyaLocalCluster):
    """Tuya local IlluminanceMeasurement cluster."""


class SensitivityLevel(t.enum8):
    """Sensitivity level enum."""

    LOW = 0x00
    MEDIUM = 0x01
    HIGH = 0x02


class OnTimeValues(t.enum8):
    """Sensitivity level enum."""

    _10_SEC = 0x00
    _30_SEC = 0x01
    _60_SEC = 0x02
    _120_SEC = 0x03


class PirMotionManufCluster(TuyaMCUCluster):
    """Neo manufacturer cluster."""

    attributes = TuyaMCUCluster.attributes.copy()
    attributes.update({0xEF09: ("sensitivity_level", SensitivityLevel)})
    attributes.update({0xEF0A: ("keep_time", OnTimeValues)})

    async def write_attributes(self, attributes, manufacturer=None):
        """Overwrite to force manufacturer code."""

        return await super().write_attributes(
            attributes, manufacturer=foundation.ZCLHeader.NO_MANUFACTURER_ID
        )

    dp_to_attribute: Dict[int, DPToAttributeMapping] = {
        1: DPToAttributeMapping(
            TuyaOccupancySensing.ep_attribute,
            "occupancy",
            dp_type=TuyaDPType.BOOL,
            converter=lambda x: IasZone.ZoneStatus.Alarm_1 if not x else 0,
        ),
        4: DPToAttributeMapping(
            TuyaPowerConfigurationCluster.ep_attribute,
            "battery_percentage_remaining",
            dp_type=TuyaDPType.VALUE,
        ),
        9: DPToAttributeMapping(
            TuyaMCUCluster.ep_attribute,
            "sensitivity_level",
            dp_type=TuyaDPType.ENUM,
            converter=lambda x: SensitivityLevel(x),
        ),
        10: DPToAttributeMapping(
            TuyaMCUCluster.ep_attribute,
            "keep_time",
            dp_type=TuyaDPType.ENUM,
            converter=lambda x: OnTimeValues(x),
        ),
        12: DPToAttributeMapping(
            TuyaIlluminanceMeasurement.ep_attribute,
            "measured_value",
            dp_type=TuyaDPType.VALUE,
            converter=lambda x: 10000 * math.log10(x) + 1 if x != 0 else 0,
        ),
    }

    data_point_handlers = {
        1: "_dp_2_attr_update",
        4: "_dp_2_attr_update",
        9: "_dp_2_attr_update",
        10: "_dp_2_attr_update",
        12: "_dp_2_attr_update",
    }


class PirMotion(CustomDevice):
    """Tuya PIR motion sensor."""

    signature = {
        MODELS_INFO: [("_TZE200_3towulqd", "TS0601")],
        ENDPOINTS: {
            # endpoints=1 profile=260 device_type=0x0402
            # in_clusters=[0x0000, 0x0001, 0x0500],
            # out_clusters=[0x000a, 0x0019]
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.IAS_ZONE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    TuyaPowerConfigurationCluster.cluster_id,
                    IasZone.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Time.cluster_id,
                    Ota.cluster_id,
                ],
            }
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.IAS_ZONE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    TuyaPowerConfigurationCluster,
                    PirMotionManufCluster,
                    TuyaOccupancySensing,
                    TuyaIlluminanceMeasurement,
                ],
                OUTPUT_CLUSTERS: [
                    Time.cluster_id,
                    Ota.cluster_id,
                ],
            }
        }
    }
```

</details>

**Comment by TheJulianJES** [comment]
Let's keep this open until it's fixed in zha-quirks (without using a custom quirk).

**Comment by jack5mikemotown** [comment]
After using this fixed quirk I can no longer see Motion, I can still see Illuminance and Occupancy

**Comment by jure123** [comment]
> After using this fixed quirk I can no longer see Motion, I can still see Illuminance and Occupancy

@jack5mikemotown, can you post your previous version of your quirk that worked for you?

**Comment by javicalle** [comment]
Neither the device or the quirk declares a `Motion` cluster. Maybe you were using another quirk before?

**Comment by adi90x** [comment]
Hello,

Seems with last release TuyaDPType is not in mcu anymore so quirk need some ajustement...

Regards,

**Comment by javicalle** [comment]
Just remove all the `dp_type=TuyaDPType.XXXXXX` from the `dp_to_attribute` part:
```python
    dp_to_attribute: Dict[int, DPToAttributeMapping] = {
        1: DPToAttributeMapping(
            MotionSensorCluster.ep_attribute,
            "zone_status",
            dp_type=TuyaDPType.BOOL,   # <-- REMOVE FROM ALL DPs
            converter=lambda x: IasZone.ZoneStatus.Alarm_1 if not x else 0,
        ),
        .../...
```

**Comment by timm-severin** [comment]
Hi, I have the same sensor, but apparently I have quite different clusters:

```json
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0402",
          "input_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0400",
            "0x0500",
            "0xe002",
            "0xef00"
          ],
          "output_clusters": []
        }
      },
      "manufacturer": "_TZE200_3towulqd",
      "model": "TS0601"
    },
```

I cannot get the quirk to work, I removed the output clusters, but I also do not really know how to deal with `0xe002` and `0xef00`. Tried removing them and whatnot, but no chance.

When I try to add the device my zha log prints the following lines:
```
[...]
2023-08-14 18:45:56.804 INFO (MainThread) [zigpy.device] [0x124b] Read model 'TS0601' and manufacturer '_TZE200_3towulqd' from <Endpoint id=1 in=[basic:0x0000, identify:0x0003, ias_zone:0x0500, None:0xE002, None:0xEF00, power:0x0001, illuminance:0x0400] out=[] status=<Status.ZDO_INIT: 1>>
2023-08-14 18:45:56.804 INFO (MainThread) [zigpy.device] [0x124b] Discovered basic device information for <Device model='TS0601' manuf='_TZE200_3towulqd' nwk=0x124B ieee=**** is_initialized=True>
2023-08-14 18:45:56.805 DEBUG (MainThread) [zigpy.application] Device is initialized <Device model='TS0601' manuf='_TZE200_3towulqd' nwk=0x124B ieee=**** is_initialized=True>
2023-08-14 18:45:56.809 DEBUG (MainThread) [zigpy.quirks.registry] Checking quirks for _TZE200_3towulqd TS0601 (****)
2023-08-14 18:45:56.809 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'ts0601_pirmotion.PirMotion'>
2023-08-14 18:45:56.809 DEBUG (MainThread) [zigpy.quirks.registry] Fail because input cluster mismatch on at least one endpoint
[...]
```

So at least I know that it tries the quirk.
